version: '3.8'

services:
  flask_app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
